name: Java CI

on: [push, pull_request]

jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run the Maven verify phase
        run: mvn -B verify

